on:
    push:
        branches-ignore:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    validate:
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
        runs-on: windows-latest

        env:
            PROJECT_NAME: ${{ github.event.repository.name }}

        steps:
            - uses: actions/checkout@v1
            - name: Install Prerequisites (Windows PowerShell 5.1)
              run: .\build\vsts-prerequisites.ps1 -ModuleName $env:PROJECT_NAME
              shell: powershell
            - name: Validate (Windows PowerShell 5.1)
              run: .\build\vsts-validate.ps1
              shell: powershell
            - name: Install Prerequisites (PowerShell 7)
              run: .\build\vsts-prerequisites.ps1 -ModuleName $env:PROJECT_NAME
              shell: pwsh
            - name: Validate (PowerShell 7)
              run: .\build\vsts-validate.ps1
              shell: pwsh
